version: 2

updates:
    - package-ecosystem: npm
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
          time: '09:00'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      commit-message:
          prefix: chore
          include: scope
      groups:
          npm-development:
              dependency-type: development
              update-types:
                  - minor
                  - patch
          npm-production:
              dependency-type: production
              update-types:
                  - minor
                  - patch
    - package-ecosystem: github-actions
      directory: /
      target-branch: dev
      schedule:
          interval: weekly
          day: monday
          time: '09:30'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      commit-message:
          prefix: chore
          include: scope
      groups:
          github-actions:
              patterns:
                  - '*'
